BEGIN;

SET ROLE kuda_ai;

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- CONTENT

CREATE TYPE content_type AS ENUM (
    'song',
    'blog',
    'til'
);

create table content (
    id integer generated by default as identity primary key,
    creation_date date,
    content_type content_type,
    content_id text,
    title text
);


-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- SONGBOOK

create table songs (
    id text primary key unique,
    artist text,
    name text,
    lyrics text,
    chords text,
    copyright text
);

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- BLOG

create table blogs (
    id serial primary key,
    path text unique not null,
    title text not null,
    body text,
    created_at DATE DEFAULT current_date,
    updated_at DATE DEFAULT current_date
);

create table tags (
    id serial primary key,
    tag text unique not null
);

create table blog_tags (
  blog_id integer references blogs(id) on delete cascade,
  tag_id integer references tags(id),
  primary key (blog_id, tag_id)
);


-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- BOOKSHELF

-- TODO: create table books ();

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- TIL

create table til (
    id serial primary key,
    path text unique not null,
    title text not null,
    content text,
    created_at date default current_date,
    updated_at date default current_date
);

CREATE TABLE til_tags (
    til_id integer not null references til(id) on delete cascade,
    tag_id integer not null references tags(id) on delete cascade,
    primary key (til_id, tag_id)
);



-- TODO: Tags??

-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-- AUTH

CREATE TABLE users (
    email VARCHAR(255) PRIMARY KEY,
    hashed_password CHAR(60) NOT NULL,
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW()
);

COMMIT;
